version: '3.8'
services:
  mjpeg-cam:
      container_name: mjpeg-cam
      build: .
      volumes:
        - /run/udev:/run/udev:ro
        - /usr/lib/python3/dist-packages/libcamera/:/usr/lib/python3/dist-packages/libcamera/
      environment:
        - LOG_LEVEL=INFO
        #- LD_LIBRARY_PATH=/usr/lib
      restart: unless-stopped
      privileged: true
      ports:
        - "8000:8000"