version: '3.8'
services:
  mjpeg-cam:
      container_name: mjpeg-cam
      build: .
      volumes:
        - /run/udev:/run/udev:ro
      environment:
        - LOG_LEVEL=INFO
      restart: unless-stopped
      privileged: true
      ports:
        - "8000:8000"